import './globals.css'
import { Inter ,Rubik } from 'next/font/google'
import Nav from '@components/Nav'
import Provider from '@components/Provider'
import Hero from '@components/Hero'
const inter = Inter({ subsets: ['latin'] })
const rubik = Rubik({ subsets: ['latin' ,'cyrillic','cyrillic-ext','hebrew'] })

export const metadata = {
  title: 'travelio-anway',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${rubik.className} px-[8px] md:px-[16px] lg:px-[32px] xl:px-[64px] `  }>
        <Provider >
       
        <Nav />
        <main className='' >

        {children}

        </main>
        </Provider>
        </body>
    </html>
  )
}
